# Generated by Django 5.0.4 on 2024-04-11 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, max_length=256, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название продукта')),
                ('description', models.TextField(max_length=256, verbose_name='Описание продукта')),
                ('size', models.CharField(max_length=10, verbose_name='Размер продукта')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес продукта (кг)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена продукта')),
                ('status', models.CharField(choices=[('In stock', 'В наличии'), ('Out of stock', 'Нет в наличии')], max_length=25, verbose_name='Статус продукта')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('product_photo', models.ImageField(blank=True, null=True, upload_to='product_photos', verbose_name='Фото продукта')),
                ('category', models.ManyToManyField(blank=True, related_name='product', to='products.category', verbose_name='Категория')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.manufacturer', verbose_name='Кому принадлежит продукт')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['id'],
            },
        ),
    ]
