# Generated by Django 5.0.4 on 2024-04-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'История заказов',
                'verbose_name_plural': 'Истории заказов',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=28, verbose_name='ПВЗ')),
                ('delivery_path', models.CharField(max_length=55, verbose_name='Путь доставки')),
                ('status', models.CharField(choices=[('Processed', 'Обрабатывается'), ('Rejection', 'Отказ'), ('Delivered', 'Доставлен'), ('Accepted', 'Принят'), ('In path', 'В пути')], default='Processed', max_length=12, verbose_name='Статус заказа')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
