# Generated by Django 5.0.4 on 2024-04-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersuser',
            name='orders',
            field=models.ManyToManyField(related_name='user_orders', to='orders.order', verbose_name='Заказ'),
        ),
    ]
