# Generated by Django 5.0.4 on 2024-04-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название населённого пункта')),
                ('coords', models.TextField(verbose_name='Координаты')),
            ],
            options={
                'verbose_name': 'Населённый пункт',
                'verbose_name_plural': 'Населённые пункты',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Склад компании',
                'verbose_name_plural': 'Склады компаний',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название компании')),
                ('cities', models.ManyToManyField(to='main.city', verbose_name='Города компании')),
            ],
            options={
                'verbose_name': 'Компания производитель',
                'verbose_name_plural': 'Компании производители',
                'ordering': ['id'],
            },
        ),
    ]
